import { pickUniform, type Rng } from '../domain/random';
import type { PlantSpecies } from './types';
import type { Lang, Localized } from '../i18n/lang';

/** Câu cây nói cả ngày: mỗi ngày chọn ngẫu nhiên một câu (câu chung + `species.sayings`). */
export const COMMON_SAYINGS: Localized<string[]> = {
  vi: [
    'Xin chào! Hôm nay mình cùng lớn nhé 🌱',
    'Ơ bạn tới rồi! Mình chờ nãy giờ á 💕',
    'Làm xong việc là tưới cho mình đó nha 💧',
    'Hôm nay bạn trông tuyệt lắm đó ✨',
    'Từng việc nhỏ thôi, mình tin bạn! 🍀',
    'Mình vừa mơ thấy bạn làm xong hết việc đó 😆',
    'Uống nước chưa? Mình uống rồi nè 💦',
    'Cùng nhau nở hoa hôm nay nha 🌸',
    'Bạn là người làm vườn số một của mình! 🏆',
    'Chậm mà chắc, mình không vội đâu 🐢',
    'Hít một hơi thật sâu rồi mình bắt đầu nha 🌬️',
    'Không cần hoàn hảo, chỉ cần tiến lên một chút thôi 💪',
    'Hôm nay nhớ cười nhiều lên nha 😊',
    'Mệt thì nghỉ một xíu, mình vẫn ở đây mà 🌿',
    'Mỗi việc bạn làm là một giọt nước cho mình 💧',
    'Bạn giỏi hơn bạn nghĩ nhiều lắm đó!',
    'Hôm nay là một trang mới tinh, viết gì cũng đẹp 📖',
    'Ăn sáng đầy đủ chưa đó? 🍳',
    'Nhớ đứng dậy vươn vai một cái nha 🙆',
    'Làm từ từ thôi, mình lớn từ từ cũng được 🌱',
    'Có bạn chăm, mình thấy vui lắm 💚',
    'Việc khó nhất làm trước, việc vui để sau nha 😉',
    'Mình gửi bạn một cái ôm lá xanh 🤗',
    'Trời hôm nay đẹp như bạn vậy ☀️',
    'Xong việc nào là mình vươn cao thêm chút xíu 📏',
    'Đừng quên uống nước và nghỉ mắt nha 👀',
    'Bạn làm được mà, mình cổ vũ nè 📣',
    'Một ngày nhẹ nhàng và thật nhiều điều xinh đẹp nha 🌷',
    'Mình chưa ra hoa, nhưng mình đang cố nè 🌼',
    'Cảm ơn bạn đã chăm mình mỗi ngày 💌',
  ],
  en: [
    'Hello! Let\'s grow together today 🌱',
    'Oh, you\'re here! I\'ve been waiting 💕',
    'Finishing a task waters me, you know 💧',
    'You look amazing today ✨',
    'One little task at a time — I believe in you! 🍀',
    'I just dreamed you finished everything 😆',
    'Had some water yet? I already did 💦',
    'Let\'s bloom together today 🌸',
    'You\'re my number one gardener! 🏆',
    'Slow and steady — I\'m in no rush 🐢',
    'Take a deep breath, then let\'s begin 🌬️',
    'No need to be perfect, just a tiny step forward 💪',
    'Remember to smile a lot today 😊',
    'Tired? Rest a bit, I\'m still right here 🌿',
    'Every task you do is a drop of water for me 💧',
    'You\'re so much better than you think!',
    'Today is a brand-new page — anything you write looks lovely 📖',
    'Did you have a good breakfast? 🍳',
    'Remember to stand up and stretch 🙆',
    'Take it slow — I can grow slowly too 🌱',
    'Being looked after by you makes me so happy 💚',
    'Hardest task first, fun ones later 😉',
    'Sending you a leafy green hug 🤗',
    'Today\'s sky is as lovely as you ☀️',
    'Every task done and I grow a teeny bit taller 📏',
    'Don\'t forget to drink water and rest your eyes 👀',
    "You can do it — I'm cheering for you 📣",
    'Wishing you a gentle day full of pretty things 🌷',
    'I haven\'t bloomed yet, but I\'m trying 🌼',
    'Thank you for caring for me every day 💌',
  ],
};

export function pickSaying(species: PlantSpecies, rng: Rng, lang: Lang): string {
  return pickUniform([...COMMON_SAYINGS[lang], ...(species.sayings?.[lang] ?? [])], rng);
}
